"""initial schema: users, briefs, personas, campaigns, variants, simulations

Revision ID: aae690e8cfc0
Revises: 
Create Date: 2026-07-07 02:25:05.168628

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aae690e8cfc0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('brand_briefs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('project_id', sa.String(length=100), nullable=True),
    sa.Column('graph_id', sa.String(length=255), nullable=True),
    sa.Column('graph_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brand_briefs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brand_briefs_user_id'), ['user_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('brand_brief_id', sa.Uuid(), nullable=True),
    sa.Column('campaign_ref', sa.String(length=100), nullable=True),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.Column('campaign_goal', sa.Text(), nullable=True),
    sa.Column('parent_campaign_id', sa.Uuid(), nullable=True),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('designer_session_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_brief_id'], ['brand_briefs.id'], ),
    sa.ForeignKeyConstraint(['parent_campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_campaign_ref'), ['campaign_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_user_id'), ['user_id'], unique=False)

    op.create_table('personas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('brand_brief_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('segment', sa.String(length=255), nullable=True),
    sa.Column('segment_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_brief_id'], ['brand_briefs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.create_index('idx_personas_user_brief', ['user_id', 'brand_brief_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_personas_brand_brief_id'), ['brand_brief_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_personas_user_id'), ['user_id'], unique=False)

    op.create_table('campaign_variants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('variant_ref', sa.String(length=100), nullable=True),
    sa.Column('variant_name', sa.String(length=255), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('content', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('target_segment', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('provenance', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_variants_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('simulations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('brand_brief_id', sa.Uuid(), nullable=True),
    sa.Column('sim_key', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('result_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_brief_id'], ['brand_briefs.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulations_sim_key'), ['sim_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulations_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulations_user_id'))
        batch_op.drop_index(batch_op.f('ix_simulations_sim_key'))

    op.drop_table('simulations')
    with op.batch_alter_table('campaign_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_variants_campaign_id'))

    op.drop_table('campaign_variants')
    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personas_user_id'))
        batch_op.drop_index(batch_op.f('ix_personas_brand_brief_id'))
        batch_op.drop_index('idx_personas_user_brief')

    op.drop_table('personas')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_user_id'))
        batch_op.drop_index(batch_op.f('ix_campaigns_campaign_ref'))

    op.drop_table('campaigns')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('brand_briefs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brand_briefs_user_id'))

    op.drop_table('brand_briefs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
