"""add brand_briefs.business_type and campaigns.objective

Revision ID: bc86bb223a1b
Revises: dc1aaf6c47c9
Create Date: 2026-07-14 02:14:05.249396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc86bb223a1b'
down_revision = 'dc1aaf6c47c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand_briefs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_type', sa.String(length=20), nullable=True))

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('objective', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_column('objective')

    with op.batch_alter_table('brand_briefs', schema=None) as batch_op:
        batch_op.drop_column('business_type')

    # ### end Alembic commands ###
