"""add rationale and hypothesis to campaign_variants

Revision ID: c934c0d6f87d
Revises: eaa8d85cb25a
Create Date: 2026-07-15 02:12:55.697864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c934c0d6f87d'
down_revision = 'eaa8d85cb25a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_variants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rationale', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('hypothesis', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_variants', schema=None) as batch_op:
        batch_op.drop_column('hypothesis')
        batch_op.drop_column('rationale')

    # ### end Alembic commands ###
